name: Docker Image CI

on:
  push:
    branches:
    - master
    - release/*

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker
      run: docker login -u "bigbeyer" -p "14752369Cb"
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bigbeyer/website_1:prod
    - name: Push the Docker image
      run: docker push bigbeyer/website_1:prod 
      
