name: Docker Image CI

on:
  pull_request:
    branches:
    - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
